# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-SimpleScan-Plugin-Snapshot
version:      0.02
version_from: lib/App/SimpleScan/Plugin/Snapshot.pm
installdirs:  site
requires:
    App::SimpleScan:               0.21
    Test::More:                    0
    WWW::Mechanize::Plugin::Snapshot: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
